cc_binary(
  name = "enough",
  srcs = [
    "enough.c",
  ],
  deps = [
    "//:zlib",
  ],
)

cc_binary(
  name = "gun",
  srcs = [
    "gun.c",
  ],
  deps = [
    "//:zlib",
  ],
)

cc_binary(
  name = "zran",
  srcs = [
    "zran.c",
  ],
  deps = [
    "//:zlib",
  ],
)
